name: Push Docker Hub (manually)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "image verision"
        required: true
        type: String

jobs:
  push_to_registry:
    name: Push image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.12.0
          run_install: true

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: backend/
          push: true
          tags: leonext/mcdonut:${{ github.event.inputs.version }}
