name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:

jobs:
  Run-L2-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install exact dependencies pnpm ci
        run: echo TODO

      - name: Run costly tests (e2e, security, ...)
        run: echo TODO
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.12.0
          run_install: false

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} --cwd frontend

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}  --cwd frontend --env VERCEL_BUILD_COMMAND="pnpm build:staging"

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --cwd frontend
