name: Vercel-Prod-Front

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  Deploy-Prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Test sh
        run: sh -c 'echo hello'

      - name: Install Vercel CLI
        run: |
          cd frontend 
          pnpm add --global vercel@latest

      - name: Pull Vercel Environment Information
        run: |
          cd frontend 
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          set -x
          cd frontend 
          echo "Starting build process..."
          echo "VERCEL_TOKEN: ${VERCEL_TOKEN}"
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          echo "Build process completed."

      - name: Deploy Project Artifacts
        run: |
          cd frontend 
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
