name: Vercel-Prod-Front

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    types:
      - opened
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  Deploy-Prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Test sh
        run: sh -c 'echo hello'

      - name: Install Vercel CLI
        run: |
          cd frontend 
          npm install --global vercel

      - name: Pull Vercel Environment Information
        run: |
          cd frontend 
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          cd frontend 
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: |
          cd frontend 
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
